title: kdlr
url: https://sailorfe.github.io
description: >-
  cell
email: krdlrosa@gmail.com
blog_path: blog
permalink: /post/:title
author: "Kathryn de la Rosa"
blurb: "b. 1997, Prestonsburg, Kentucky"

# Build settings
markdown: kramdown
plugins:
  - github-pages
  - jekyll-feed