title: kdlr
url: https://sailorfe.github.io
description: >-
  cell
email: krdlrosa@gmail.com
blog_path: blog
permalink: /post/:title

# Build settings
markdown: kramdown
plugins:
  - github-pages
  - jekyll-feed